### PR TITLE
Add swap() tests for Pool 2

### PR DESCRIPTION
**Pull request by dubzn**
This PR adds the swap tests corresponding to the Pool 2, resolving issue #163

### CODE REVIEW

**Review by uri-99 — APPROVED** [review]

**Review by dpinones — APPROVED** [review]
Great work! 🚀

**Comment by rcatalan98** [comment]
Hey, great work! I just see two things that look like they were added somewhere because I don't see it in the file changes.
1. When you run the tests there is a "case" printed constantly.
2. There is a test that for some reason it takes too long to finish? Do you know why?

**Review by rcatalan98 — APPROVED** [review]
Hey, great work! I just see two things that look like they were added somewhere because I don't see it in the file changes.

When you run the tests there is a "case" printed constantly.
There is a test that for some reason it takes too long to finish? Do you know why?

**Comment by rcatalan98** [comment]
> Hey, great work! I just see two things that look like they were added somewhere because I don't see it in the file changes.
> 
> When you run the tests there is a "case" printed constantly. There is a test that for some reason it takes too long to finish? Do you know why?

Never mind we are going to address this after all the debugging "hacks" are no longer needed.

**Pull request merged**
