### PR TITLE
Add flash to YASPool

### PR DESCRIPTION
**Pull request by berwingan**
Resolves: #92 

Add the flash function to the YasPool contract with accompanying interface.

### CODE REVIEW

**Comment by rcatalan98** [comment]
Hi @berwingan thanks for collaborating with YAS! Could you add tests to this function? We usually port the same tests UniswapV3 has. You can take a look at them [here](https://github.com/Uniswap/v3-core/blob/main/test/UniswapV3Pool.spec.ts#L1397). Just with a few of them to check things are working is fine (we can leave some tests as TODO for other Issues).
Let me know if you have any questions.

**Comment by rcatalan98** [comment]
Hey @berwingan are you going to keep working on this PR?

**Comment by berwingan** [comment]
@rcatalan98 hey I don't think I will be able to continue working on this, please reject the pr

**Comment by rcatalan98** [comment]
> @rcatalan98 hey I don't think I will be able to continue working on this, please reject the pr

Ok no problem. Thanks for trying anyway! You are more than welcome to collaborate in the future if you want. Let us know!

**Pull request closed without merging**
