### PR TITLE
fix: add pop_log_with_key  to fix test issue

### PR DESCRIPTION
**Pull request by codeWhizperer**

### CODE REVIEW

**Comment by WiseMrMusa** [comment]
The PR is falling format test

You can run `sscarb fmt --check` to check the formatting rules

**Comment by codeWhizperer** [comment]
> The PR is falling format test
> 
> You can run `scarb fmt --check` to check the formatting rules

Yeah, I just formatted it now and made a commit

**Comment by dubzn** [comment]
Hey @codeWhizperer thanks for your contribution! 
Great job! We've been analyzing the change, and based on that, we deployed two contracts (one from the main branch and another from this branch). We noticed that the events are not displaying correctly. We believe that the #[key] tag is relatively new and might not be functioning as expected yet, so we've decided to postpone this for the future.

Your PR was a significant help in reaching this conclusion!

### Links
- [Starkscan main-contract](https://testnet.starkscan.co/contract/0x0701198b5f55f55caf7c0079758f3fa95528f82f11563d9b21767cf6e8ae8ff4#events) (events without #[key] tag)
- [Starkscan fix-test-event-contract](https://testnet.starkscan.co/contract/0x029839b704ff0fec573caf22c9915751159db88c0eb3857ba7058805daddd374#events)

### Images
- main-contract
image

- fix-test-event-contract
image

**Comment by rcatalan98** [comment]
Check this [comment](https://github.com/lambdaclass/yet-another-swap/pull/110#issuecomment-1736092232).

**Pull request closed without merging**
